### PR TITLE
Rename deploy script

### PR DESCRIPTION
**Pull request by eistrati**

### CODE REVIEW

**Comment by vcalmic** [comment]
approve

**Comment by vcalmic** [comment]
approve

**Comment by vcalmic** [comment]
approve

**Comment by vcalmic** [comment]
approve

**Comment by vcalmic** [comment]
approve

**Comment by vcalmic** [comment]
approve

**Comment by vcalmic** [comment]
approve

**Comment by vcalmic** [comment]
approve

**Comment by vcalmic** [comment]
approve

**Comment by eistrati** [comment]
not relevant anymore

**Pull request closed without merging**
